apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec: 
  selector:
    matchLabels:
      app: goserver
  replicas: 2
  template:
    metadata:
      labels:
        app: "goserver" 
    spec:
      containers:
        - name: goserver
          image: "joviniano/hello-go:v5" 
          env: 
            - name: NAME
              value: "Joviniano"    
