apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  capacity:
    storage: 50gb
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce  # pods dentro do mesmo Node
    - ReadWriteMany 